# Generated by Django 5.0 on 2023-12-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('detailed_description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Подробное описание')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=50, verbose_name='Статус')),
            ],
        ),
    ]
