# Generated by Django 4.2.7 on 2023-12-15 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2022-12-12', verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='detailed_description',
            field=models.TextField(blank=True, default='2022-12-12', verbose_name='Детальное описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='to_do_list.type', verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='to_do_list.status', verbose_name='Статус'),
        ),
    ]
